import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		double rand =0;
		boolean boy = false;
		boolean girl = false;
		int count = 0;
		int fam2 = 0, fam3 = 0, fam4 =0;
		double averg = 0;
		int countT = 0;
		while(T != countT){
			boy = false;
			girl = false;
			count = 0;
			while(boy != true || girl != true){
				rand = generator.nextDouble();
				if(rand<0.5){
					boy =true;
				}
				else{
					girl = true;
				}
				count++;
			}
			if(count == 2){
				fam2++;
			}
			else if(count == 3){
				fam3++;
			}
			else{
				fam4++;
			}
			averg = averg + count;
			countT++;
		}
		averg = averg / T;
		System.out.println("Average: "+ averg+" children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+fam2);
		System.out.println("Number of families with 3 children: "+fam3);
		System.out.println("Number of families with 4 or more children: "+fam4); 

		if(fam2 > fam3 && fam2>fam4){
			System.out.println("The most common number of children is 2.");
		}
		else if(fam3 > fam2 && fam3 > fam4){
			System.out.println("The most common number of children is 3.");
		}
		else{
			System.out.println("The most common number of children is 4.");

		}

	}
}
